name: efood_multivendor_driver
description: A new Flutter application.
publish_to: 'none'
version: 1.1.6+18

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.2.2
  connectivity: ^3.0.6
#  firebase_core: ^1.17.1
  # firebase_core: ^2.4.1
  firebase_core: 
#  firebase_messaging: ^11.4.1
  # firebase_messaging: ^14.2.1
  firebase_messaging: 
  # firebase_core_platform_interface: 4.5.2
  firebase_core_platform_interface:
  flutter_local_notifications: ^16.3.0
  path_provider: ^2.1.2
  url_strategy: ^0.2.0
  pin_code_fields: ^8.0.1
  http: ^1.1.2
  flutter_switch: ^0.3.2
  shimmer_animation: ^2.1.0+1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.2
  url_launcher: ^6.2.3
  vibration: ^1.8.4
  image_picker: ^1.0.7
  disable_battery_optimization: ^1.1.1
  phone_number: ^2.0.1
  country_code_picker: ^3.0.0
  location: ^5.0.3
  audioplayers: 
  flutter_widget_from_html_core: ^0.14.11
  fwfh_text_style: ^2.23.8
  firebase_crashlytics: ^3.4.9

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900